import { ArrowDownLeft, ArrowUpRight, Lightbulb, Sparkles, WalletCards } from "lucide-react";
import { foundationMock } from "@/lib/mocks";
import { Badge, Button, Card, Chip, MetricCard, ProgressBar } from "@/components/ui/fox";
import QuickEntryModal from "@/components/dashboard/QuickEntryModal";
import { useState } from "react";

export default function FoundationHome() {
  const [entryType, setEntryType] = useState(null);
  const quickActions = [{ type: "expense", label: "Despesa", tone: "negative", symbol: "−" }, { type: "income", label: "Receita", tone: "positive", symbol: "+" }, { type: "card", label: "Cartão", tone: "card", symbol: "▣" }, { type: "investment", label: "Invest.", tone: "positive", symbol: "↗" }];
  return <div className="fox-page">
    <section className="fox-hero fox-rise"><div><span className="fox-eyebrow">Quarta-feira, 12 de junho</span><h1 className="fox-display fox-hero-title">Olá, Rafael<span className="fox-primary">.</span></h1><p className="fox-muted">Vamos deixar sua vida financeira mais leve?</p></div><div className="fox-hero-mark"><Sparkles size={20} /></div></section>
    <section className="fox-balance fox-card fox-rise fox-delay-1" data-testid="balance-summary"><div className="fox-balance-label"><span>Saldo disponível</span><Badge tone="positive">+12,4%</Badge></div><strong data-testid="balance-value">{foundationMock.balance}</strong><div className="fox-balance-foot"><span className="fox-muted">em todas as contas</span><WalletCards size={18} /></div></section>
    <section className="fox-quick-actions fox-rise fox-delay-1" aria-label="Adicionar lançamento" data-testid="dashboard-quick-actions">{quickActions.map((action) => <button key={action.type} className={`fox-quick-action ${action.tone}`} onClick={() => setEntryType(action.type)} data-testid={`quick-action-${action.type}`}><span>{action.symbol}</span><strong>{action.label}</strong></button>)}</section>
    <section className="fox-section fox-rise fox-delay-2"><div className="fox-section-heading"><div><span className="fox-eyebrow">Visão geral</span><h2>Seu mês até aqui</h2></div><button className="fox-text-button" data-testid="overview-period-button">Junho <span>⌄</span></button></div><div className="fox-metric-grid"><MetricCard label="Entradas" value="R$ 8.100,00" detail="+8,2% vs. maio" tone="positive" icon={<ArrowDownLeft size={17} />} /><MetricCard label="Despesas" value="R$ 2.480,20" detail="−3,6% vs. maio" tone="negative" icon={<ArrowUpRight size={17} />} /></div></section>
    <section className="fox-section fox-rise fox-delay-3"><div className="fox-section-heading"><div><span className="fox-eyebrow">Atalhos</span><h2>Explore a fundação</h2></div></div><div className="fox-chips"><Chip active data-testid="foundation-chip-overview">Visão geral</Chip><Chip data-testid="foundation-chip-timeline">Timeline</Chip><Chip data-testid="foundation-chip-planning">Planejamento</Chip></div></section>
    <section className="fox-insight fox-card fox-rise fox-delay-3" data-testid="insight-card"><div className="fox-insight-icon"><Lightbulb size={20} /></div><div><span className="fox-eyebrow">Insight Fox</span><p>{foundationMock.insight}</p><ProgressBar value={68} /></div></section>
    <section className="fox-section fox-rise fox-delay-3"><div className="fox-section-heading"><div><span className="fox-eyebrow">Exemplo visual</span><h2>Últimas movimentações</h2></div><Button variant="ghost" data-testid="view-all-movements-button">Ver todas</Button></div><Card className="fox-activity-list">{foundationMock.entries.map((entry) => <div className="fox-activity" key={entry.label} data-testid={`movement-${entry.type}`}><div className={`fox-activity-icon ${entry.type}`}>{entry.type === "positive" ? <ArrowDownLeft size={17} /> : <ArrowUpRight size={17} />}</div><div className="fox-activity-copy"><strong>{entry.label}</strong><span>{entry.detail}</span></div><strong className={`fox-activity-value ${entry.type}`}>{entry.value}</strong></div>)}</Card></section>
    {entryType && <QuickEntryModal type={entryType} onClose={() => setEntryType(null)} />}
  </div>;
}