import { ArrowDownLeft, ArrowUpRight, BellRing, BriefcaseBusiness, CreditCard, Lightbulb, Sparkles, WalletCards } from "lucide-react";
import { foundationMock } from "@/lib/mocks";
import { Badge, Button, Card, MetricCard, ProgressBar } from "@/components/ui/fox";
import QuickEntryModal from "@/components/dashboard/QuickEntryModal";
import { useState } from "react";
import { Link } from "react-router-dom";
import InsightsPanel from "@/components/dashboard/InsightsPanel";

export default function FoundationHome() {
  const [entryType, setEntryType] = useState(null);
  const [showInsights, setShowInsights] = useState(false);
  const quickActions = [{ type: "expense", label: "Despesa", tone: "negative", icon: ArrowDownLeft }, { type: "income", label: "Receita", tone: "positive", icon: ArrowUpRight }, { type: "card", label: "Cartão", tone: "card", icon: CreditCard }, { type: "investment", label: "Invest.", tone: "positive", icon: BriefcaseBusiness }];
  return <div className="fox-page">
    <section className="fox-hero fox-rise"><div><span className="fox-eyebrow">Quarta-feira, 12 de junho</span><h1 className="fox-display fox-hero-title">Olá, Rafael<span className="fox-primary">.</span></h1><p className="fox-muted">Vamos deixar sua vida financeira mais leve?</p></div><button className="fox-hero-mark" onClick={() => setShowInsights(true)} aria-label="Abrir insights" data-testid="insights-trigger"><Sparkles size={20} /></button></section>
    <section className="fox-balance fox-card fox-rise fox-delay-1" data-testid="balance-summary"><div className="fox-balance-label"><span>Saldo disponível</span><Badge tone="positive">+12,4%</Badge></div><strong data-testid="balance-value">{foundationMock.balance}</strong><Link className="fox-balance-foot" to="/accounts" data-testid="balance-accounts-link"><span>em todas as contas</span><WalletCards size={18} /></Link></section>
    <section className="fox-quick-actions fox-rise fox-delay-1" aria-label="Adicionar lançamento" data-testid="dashboard-quick-actions">{quickActions.map(({ type, label, tone, icon: Icon }) => <button key={type} className={`fox-quick-action ${tone}`} onClick={() => setEntryType(type)} data-testid={`quick-action-${type}`}><span><Icon size={17} /></span><strong>{label}</strong></button>)}</section>
    <section className="fox-section fox-rise fox-delay-2"><div className="fox-section-heading"><div><span className="fox-eyebrow">Visão geral</span><h2>Seu mês até aqui</h2></div><button className="fox-text-button" data-testid="overview-period-button">Junho <span>⌄</span></button></div><div className="fox-metric-grid"><MetricCard label="Entradas" value="R$ 8.100,00" detail="+8,2% vs. maio" tone="positive" icon={<ArrowDownLeft size={17} />} /><MetricCard label="Despesas" value="R$ 2.480,20" detail="−3,6% vs. maio" tone="negative" icon={<ArrowUpRight size={17} />} /></div></section>
    <section className="fox-section fox-rise fox-delay-3"><div className="fox-section-heading"><div><span className="fox-eyebrow">Atalhos</span><h2>Explore o Fox</h2></div></div><div className="fox-chips"><Link className="fox-chip is-active" to="/" data-testid="foundation-chip-overview">Visão geral</Link><Link className="fox-chip" to="/timeline" data-testid="foundation-chip-timeline">Timeline</Link><Link className="fox-chip" to="/planning" data-testid="foundation-chip-planning">Planejamento</Link></div></section>
    <button className="fox-insight fox-card fox-rise fox-delay-3" onClick={() => setShowInsights(true)} data-testid="insight-card"><div className="fox-insight-icon"><Lightbulb size={20} /></div><div><span className="fox-eyebrow">Insight Fox</span><p>{foundationMock.insight}</p><ProgressBar value={68} /></div><BellRing className="fox-insight-bell" size={17} /></button>
    <section className="fox-section fox-rise fox-delay-3"><div className="fox-section-heading"><div><span className="fox-eyebrow">Exemplo visual</span><h2>Últimas movimentações</h2></div><Button variant="ghost" data-testid="view-all-movements-button">Ver todas</Button></div><Card className="fox-activity-list">{foundationMock.entries.map((entry) => <div className="fox-activity" key={entry.label} data-testid={`movement-${entry.type}`}><div className={`fox-activity-icon ${entry.type}`}>{entry.type === "positive" ? <ArrowDownLeft size={17} /> : <ArrowUpRight size={17} />}</div><div className="fox-activity-copy"><strong>{entry.label}</strong><span>{entry.detail}</span></div><strong className={`fox-activity-value ${entry.type}`}>{entry.value}</strong></div>)}</Card></section>
    {entryType && <QuickEntryModal type={entryType} onClose={() => setEntryType(null)} />}
    {showInsights && <InsightsPanel onClose={() => setShowInsights(false)} />}
  </div>;
}