import { ArrowLeft, BanknoteArrowDown, CalendarDays, CreditCard, History, ReceiptText } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { toast } from "sonner";
import { Button, Card } from "@/components/ui/fox";
import { peopleMock } from "@/lib/peopleMocks";

export default function PersonProfile() {
  const { personId } = useParams();
  const navigate = useNavigate();
  const person = peopleMock.find((item) => item.id === personId) || peopleMock[0];
  const isReceivable = person.status === "receivable";
  const register = (action) => toast.success(`${action} registrado (MOCK) para ${person.name}`);
  return <div className="fox-page person-profile-page"><button className="person-back" onClick={() => navigate("/people")} data-testid="person-profile-back-button"><ArrowLeft size={18} /> Pessoas</button><section className="person-profile-hero"><div className="person-profile-avatar"><span>{person.initials}</span></div><h1>{person.name}</h1><span className="fox-muted">Última atividade: {person.detail.split("·")[1] || "recentemente"}</span><div className={`person-balance ${person.status}`}><span>{isReceivable ? "TE DEVE" : person.status === "payable" ? "VOCÊ DEVE" : "SEM PENDÊNCIAS"}</span><strong>{person.balance}</strong></div><div className="person-actions">{isReceivable ? <Button onClick={() => register("Recebimento")} data-testid="register-receipt-button"><BanknoteArrowDown size={16} />Registrar recebimento</Button> : <Button onClick={() => register("Pagamento")} data-testid="register-payment-button"><BanknoteArrowDown size={16} />Paguei</Button>}<Button variant="secondary" onClick={() => toast.info("Lembrete criado (MOCK)")} data-testid="person-reminder-button">Lembrar</Button></div></section><section className="person-section"><div className="person-section-title"><span className="fox-eyebrow">Pendentes</span><span>{person.pending.length} itens</span></div>{person.pending.length ? <Card className="person-events">{person.pending.map((item) => <div className="person-event" key={item.title}><span className={`person-event-dot ${isReceivable ? "positive" : "negative"}`} /><div><strong>{item.title}</strong><span>{item.date} · {person.card ? "Cartão" : "Lançamento"}</span></div><strong className={isReceivable ? "positive" : "negative"}>{item.value}</strong></div>)}{person.card && <div className="person-card-detail" data-testid="person-card-detail"><CreditCard size={16} /><span>{person.card.bank} •••• {person.card.lastFour}<small>{person.card.description} · {person.card.date} · {person.card.forecast}</small></span></div>}</Card> : <Card className="person-empty"><ReceiptText size={17} />Nenhuma pendência em aberto</Card>}</section><section className="person-section"><div className="person-section-title"><span className="fox-eyebrow">Histórico</span><History size={16} /></div><Card className="person-events">{person.history.length ? person.history.map((item) => <div className="person-event history" key={item.title}><CalendarDays size={16} /><div><strong>{item.title}</strong><span>{item.date}</span></div><strong>{item.value}</strong></div>) : <div className="person-empty">Nenhum histórico ainda</div>}</Card></section></div>;
}