// MOCK data for /cards screen. Isolated so it can be swapped for Supabase later.
// Amounts are stored in cents to match the app's numeric(14,2) convention.

export const cardsMock = [
  {
    id: "nubank-roxinho",
    apelido: "Nubank Roxinho",
    bank: "Nubank",
    lastFour: "4832",
    brandKey: "nubank",
    limitTotal: 800000, // R$ 8.000,00
    closingDay: 3,
    dueDay: 10,
    transactions: [
      {
        id: "nu-1",
        merchant: "Ramen Boa Vista",
        category: "food",
        dateLabel: "5 ago",
        dateISO: "2025-08-05",
        amount: 6850,
        installmentsTotal: 1,
        installmentsPaid: 0,
      },
      {
        id: "nu-2",
        merchant: "Uber",
        category: "transport",
        dateLabel: "5 ago",
        dateISO: "2025-08-05",
        amount: 2490,
        installmentsTotal: 1,
        installmentsPaid: 0,
      },
      {
        id: "nu-3",
        merchant: "Drogasil",
        category: "health",
        dateLabel: "1 ago",
        dateISO: "2025-08-01",
        amount: 8720,
        installmentsTotal: 1,
        installmentsPaid: 0,
      },
      {
        id: "nu-4",
        merchant: "Zara",
        category: "shopping",
        dateLabel: "31 jul",
        dateISO: "2025-07-31",
        amount: 104970,
        installmentsTotal: 3,
        installmentsPaid: 0,
      },
      {
        id: "nu-5",
        merchant: "Netflix",
        category: "subscription",
        dateLabel: "28 jul",
        dateISO: "2025-07-28",
        amount: 5590,
        installmentsTotal: 1,
        installmentsPaid: 0,
      },
      {
        id: "nu-6",
        merchant: "Kalunga",
        category: "shopping",
        dateLabel: "22 jul",
        dateISO: "2025-07-22",
        amount: 47800,
        installmentsTotal: 4,
        installmentsPaid: 1,
      },
    ],
  },
  {
    id: "inter",
    apelido: "Banco Inter",
    bank: "Banco Inter",
    lastFour: "7291",
    brandKey: "inter",
    limitTotal: 500000, // R$ 5.000,00
    closingDay: 15,
    dueDay: 22,
    transactions: [
      {
        id: "in-1",
        merchant: "iFood",
        category: "food",
        dateLabel: "6 ago",
        dateISO: "2025-08-06",
        amount: 4290,
        installmentsTotal: 1,
        installmentsPaid: 0,
      },
      {
        id: "in-2",
        merchant: "Posto Shell",
        category: "transport",
        dateLabel: "4 ago",
        dateISO: "2025-08-04",
        amount: 18000,
        installmentsTotal: 1,
        installmentsPaid: 0,
      },
      {
        id: "in-3",
        merchant: "Amazon",
        category: "shopping",
        dateLabel: "30 jul",
        dateISO: "2025-07-30",
        amount: 89900,
        installmentsTotal: 6,
        installmentsPaid: 0,
      },
    ],
  },
  {
    id: "xp",
    apelido: "XP Investimentos",
    bank: "XP Investimentos",
    lastFour: "0912",
    brandKey: "xp",
    limitTotal: 1500000, // R$ 15.000,00
    closingDay: 20,
    dueDay: 28,
    transactions: [
      {
        id: "xp-1",
        merchant: "Latam Passagens",
        category: "travel",
        dateLabel: "2 ago",
        dateISO: "2025-08-02",
        amount: 189000,
        installmentsTotal: 10,
        installmentsPaid: 2,
      },
      {
        id: "xp-2",
        merchant: "Apple Store",
        category: "shopping",
        dateLabel: "18 jul",
        dateISO: "2025-07-18",
        amount: 599900,
        installmentsTotal: 12,
        installmentsPaid: 1,
      },
    ],
  },
];
